version: '3.3'
services:
  docker-risk_base:
   restart: always
   container_name: risk_base
   image: mariadb
   environment:
    MYSQL_DATABASE: helloDocker
    MYSQL_ROOT_PASSWORD: root
    MYSQL_ROOT_HOST: '%'
   volumes:
    - ./sql:/docker-entrypoint-initdb.d
   ports:
    - "6033:3306"
    
  docker-app:
   restart: on-failure
   build:
    context: .
    dockerfile: ./DOCKERFILE
   expose:
    - "8880"
   ports:
    - 8088:8880
   environment:
    WAIT_HOSTS: mariadb:3306
   depends_on:
    - docker-risk_base
    

   
   